=== deanm1278/blackfin-plus-gnu/openocd/openocd/openocd_memory_map.dtd
<!-- The root element of a memory map is <memory-map>.  -->

<!ELEMENT memory-map	(processor)>
<!ATTLIST memory-map	version		CDATA	#FIXED "1.0">

<!ELEMENT processor		(core, memory)>
<!ATTLIST processor		name		CDATA	#REQUIRED>

<!ELEMENT core			(memory)>
<!ATTLIST core			name		CDATA	#REQUIRED
						start		CDATA	#REQUIRED
						length		CDATA	#REQUIRED>

<!ELEMENT memory		(property)>
<!ATTLIST memory		name		CDATA	#REQUIRED
						start		CDATA	#REQUIRED
						length		CDATA	#REQUIRED
						access		CDATA	#REQUIRED>

<!ELEMENT property		(#PCDATA)>
<!ATTLIST property		name		CDATA	#REQUIRED>

=== deanm1278/blackfin-plus-gnu/include/target/bf70x_memory_map.xml
<?xml version="1.0"?>
<!DOCTYPE memory-map SYSTEM "openocd_memory_map.dtd">
<memory-map>
    <processor name="bf537">
        <memory     name="async_mem"       start="0x20000000" length="0x400000"   access="rw" />
        <memory     name="boot_rom"        start="0xef000000" length="0x800"      access="ro" />
        <memory     name="l1"              start="0xff800000" length="0x400000" />
        <core start="0xff800000" length="0x400000">
            <memory name="l1"              start="0xff800000" length="0x400000" />
            <memory name="l1_data_a"       start="0xff800000" length="0x4000"     access="rw">
                <property name="bank">"a"</property>
            </memory>
            <memory name="l1_data_a_cache" start="0xff804000" length="0x4000"     access="dcache">
                <property name="bank">"a"</property>
            </memory>
            <memory name="l1_data_b"       start="0xff900000" length="0x4000"     access="rw">
                <property name="bank">"b"</property>
            </memory>
            <memory name="l1_data_b_cache" start="0xff904000" length="0x4000"     access="dcache">
                <property name="bank">"b"</property>
            </memory>
            <memory name="l1_code"         start="0xffa00000" length="0x10000"    access="itest" />
            <memory name="l1_code_cache"   start="0xffa10000" length="0x4000"     access="icache" />
            <memory name="l1_scratch"      start="0xffb00000" length="0x1000"     access="rw" />
        </core>
        <memory     name="sysmmr"          start="0xffc00000" length="0x200000"   access="mmr" />
        <memory     name="coremmr"         start="0xffe00000" length="0x200000"   access="mmr" />
    </processor>
</memory-map>
